main/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from usuarios.views import HomeView, ProfileUpate, PostView, LoginView, SignUpView, PostFormView, LogOutView, profile, PostViewDetail, BlogPostLike, lista_usuarios

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('',login_required(HomeView.as_view(), login_url='login'), name='home'),
    path('profile/', profile, name='profile' ),
    path('profile/update', ProfileUpate.as_view(), name='profile_update'),
    path('login/', LoginView.as_view(), name='login' ),
    path('register/', SignUpView.as_view(), name='register' ),
    path('postform/', PostFormView.as_view(), name='postform' ),
    path('logout/', LogOutView.as_view(), name='logout' ),
    path('post/<str:pk>/', PostViewDetail.as_view(), name='post_detail'),
    path('blogpost-like/<int:pk>', BlogPostLike, name="blogpost_like"),
    path('friendship/', include('friendship.urls')),
    path('lista_usuarios/', lista_usuarios, name='lista_usuarios')


]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=200, blank=False)
    date_create = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=40)
    likes = models.ManyToManyField(User, related_name='post_like')


    class Meta:
        ordering = ['-date_create']

    @property
    def view_count(self):
        return Like.objects.filter(post=self).count()

    @property
    def cantidad_comentarios(self):
        return Comment.objects.filter(post=self).count()

    @property
    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=200, blank=False)
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ', ' + self.post.content[:40]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.jpg', upload_to='profiles', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    link = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.user)

usuarios/forms.py
from django.forms import ModelForm
from usuarios.models import Post, Comment, Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, User
from django.contrib.auth.forms import AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        widgets = {
          'content': forms.Textarea(attrs={'rows':3,  'placeholder':"What are you thinking?"}),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'email',
            'password1',
            'password2',
            ButtonHolder(
            Submit('register', 'Register', css_class='btn-primary')
            )
        )

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(

            Submit('login', 'Login', css_class='btn-primary')
            )
        )
#
# class UserEditForm(UserChangeForm):
#     password = None
#
#     class Meta:
#         model = Profile
#         fields = ['username', 'email', 'first_name', 'last_name' ]
#         widgets = {
#             'username': forms.TextInput(attrs={'readonly': 'readonly'}),
#             'email': forms.TextInput(attrs={'readonly': 'readonly'})
#         }


class UserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout('username', 'password', ButtonHolder(
                    Submit('Edit', 'Edit', css_class='btn-primary')
                )
            )

usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.shortcuts import render
from django.views.generic import TemplateView, View, DetailView,CreateView, ListView, FormView, RedirectView
from django.views.generic.edit import UpdateView
from usuarios.models import Post, Comment, Profile
from usuarios.forms import PostForm, RegistrationForm, LoginForm, CommentForm, UserEditForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from friendship.models import Friend, Follow, Block
from django.contrib.auth.decorators import login_required


# Create your views here.
class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['form'] = PostForm()
        return context

# def post_detail(request, id):
#     template_name = 'post_detail.html'
#     post = get_object_or_404(Post, id=id)
#     comments = get_object_or_404(Comment, id=id)
#     new_comment = None
#     # Comment posted
#     if request.method == 'POST':
#         comment_form = CommentForm(data=request.POST)
#         if comment_form.is_valid():

#             # Create Comment object but don't save to database yet
#             new_comment = comment_form.save(commit=False)
#             # Assign the current post to the comment
#             new_comment.post = post
#             # Save the comment to the database
#             new_comment.save()
#     else:
#         comment_form = CommentForm()

#     return render(request, template_name, {'post': post,
#                                            'comments': comments,
#                                            'new_comment': new_comment,
#                                            'comment_form': comment_form})

class PostViewDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        comments_connected = Comment.objects.filter(post=self.get_object()).order_by('-date_create')
        data['comments'] = comments_connected
        if self.request.user.is_authenticated:
            data['comment_form'] = CommentForm(instance=self.request.user)

        def get_context_data(self, **kwargs):
            data = super().get_context_data(**kwargs)
            likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
            liked = False
            if likes_connected.likes.filter(id=self.request.user.id).exists():
                liked = True
            data['number_of_likes'] = likes_connected.number_of_likes()
            data['post_is_liked'] = liked
            likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
            liked = False
            if likes_connected.likes.filter(id=self.request.user.id).exists():
                liked = True
            data['number_of_likes'] = likes_connected.number_of_likes()
            data['post_is_liked'] = liked

        return data


    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content'),user=self.request.user, post=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)
    # def post(self, request, **kwargs):
    #     post = Post.objects.get(pk=self.kwargs.get("pk"))
    #     form = self.form(request.POST or None, instance=post)
    #     if form.is_valid():
    #         form.save()
    #     return reverse('post-detail', kwargs={'pk': post.pk})

        # def form_valid(self,form,*args,**kwargs):
        # self.object = form.save(commit = False)
        # self.object.user = self.request.user
        # self.object.save()
        # return super().form_valid(form)

class PostFormView(FormView):
    template_name = 'home.html'
    form_class = PostForm
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class PostView(TemplateView):
    template_name = 'post.html'

class SignUpView(CreateView):
    form_class = RegistrationForm
    model = User
    template_name = 'register.html'
    success_url = reverse_lazy( 'home' )

class LoginView(FormView):
    form_class = LoginForm
    success_url = reverse_lazy('home')
    template_name = 'login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class LogOutView(RedirectView):
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super (LogOutView, self).get(request, *args, **kwargs)


# class Profile(DetailView):
#     template_name = 'profile.html'
#     model = User
#     def get_object(self, queryset=None):
#         return self.request.user

def profile(request, pk=None):
        if pk:
            user = get_object_or_404(User, pk=pk)
            posts=Post.objects.filter(user=request.user)

        else:
            user = request.user
            posts=Post.objects.filter(user=request.user)
        return render(request, 'profile.html', {'user': user, 'posts': posts})




def BlogPostLike(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('blogpost_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return HttpResponseRedirect(reverse('post_detail', args=[str(pk)]))

def lista_usuarios(request):
    amigos = Friend.objects.friends(request.user)
    followers = Follow.objects.followers(request.user)
    followings =Follow.objects.following(request.user)
    friendship_requests = Friend.objects.requests(request.user)
    context = {'amigos': amigos,
               'followers': followers,
               'followings': followings,
               'friendship_requests' : friendship_requests}

    return render(request, 'lista_usuarios.html', context)


# def edit_profile(request):
#     if request.method == "POST":
#         form = UserEditForm(request.POST)
#         if form.is_valid():
#             new_username = form.cleaned_data.get('username')
#             new_password = form.cleaned_data.get('password')
#             user = User.objects.get(username=request.user.username)
#             all_user = allusers.objects.get(user=user)
#             user.username = new_username
#             user.set_password(new_password)
#             user.save()
#             return redirect('profile.html', {'form': form} )
#
# class EditarProfile(FormView):
#     template_name = 'profile-edit.html'
#     form_class = UserEditForm
#     success_url = 'profile/'
#
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         form.save()
#         return super().form_valid(form)

@method_decorator (login_required, name='dispatch')
class ProfileUpate(UpdateView):
    model = Profile
    fields = ['avatar', 'bio', 'link']
    template_name = 'profile-edit.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        profile, created = Profile.objects.get_or_create(user=self.request.user)
        return profile

usuarios/templates/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

usuarios/templates/base.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Pagina de Pruebas Post</title>

    <style>
    body {
            background-color: #eeeeee;
        }

        .h7 {
            font-size: 0.8rem;
        }

        .gedf-wrapper {
            margin-top: 0.97rem;
        }

        @media (min-width: 992px) {
            .gedf-main {
                padding-left: 4rem;
                padding-right: 4rem;
            }
            .gedf-card {
                margin-bottom: 2.77rem;
            }
        }

        /**Reset Bootstrap*/
        .dropdown-toggle::after {
            content: none;
        }
    body{
    background-color: #f4f7f6;
    margin-top:20px;
}
.card {
    background: #fff;
    transition: .5s;
    border: 0;
    margin-bottom: 30px;
    border-radius: .55rem;
    position: relative;
    width: 100%;
    box-shadow: 0 1px 2px 0 rgb(0 0 0 / 10%);
}
.card .body {
    color: #444;
    padding: 20px;
    font-weight: 400;
}
.card .header {
    color: #444;
    padding: 20px;
    position: relative;
    box-shadow: none;
}
.single_post {
    -webkit-transition: all .4s ease;
    transition: all .4s ease
}

.single_post .body {
    padding: 30px
}

.single_post .img-post {
    position: relative;
    overflow: hidden;
    max-height: 500px;
    margin-bottom: 30px
}

.single_post .img-post>img {
    -webkit-transform: scale(1);
    -ms-transform: scale(1);
    transform: scale(1);
    opacity: 1;
    -webkit-transition: -webkit-transform .4s ease, opacity .4s ease;
    transition: transform .4s ease, opacity .4s ease;
    max-width: 100%;
    filter: none;
    -webkit-filter: grayscale(0);
    -webkit-transform: scale(1.01)
}

.single_post .img-post:hover img {
    -webkit-transform: scale(1.02);
    -ms-transform: scale(1.02);
    transform: scale(1.02);
    opacity: .7;
    filter: gray;
    -webkit-filter: grayscale(1);
    -webkit-transition: all .8s ease-in-out
}

.single_post .img-post:hover .social_share {
    display: block
}

.single_post .footer {
    padding: 0 30px 30px 30px
}

.single_post .footer .actions {
    display: inline-block
}

.single_post .footer .stats {
    cursor: default;
    list-style: none;
    padding: 0;
    display: inline-block;
    float: right;
    margin: 0;
    line-height: 35px
}

.single_post .footer .stats li {
    border-left: solid 1px rgba(160, 160, 160, 0.3);
    display: inline-block;
    font-weight: 400;
    letter-spacing: 0.25em;
    line-height: 1;
    margin: 0 0 0 2em;
    padding: 0 0 0 2em;
    text-transform: uppercase;
    font-size: 13px
}

.single_post .footer .stats li a {
    color: #777
}

.single_post .footer .stats li:first-child {
    border-left: 0;
    margin-left: 0;
    padding-left: 0
}

.single_post h3 {
    font-size: 20px;
    text-transform: uppercase
}

.single_post h3 a {
    color: #242424;
    text-decoration: none
}

.single_post p {
    font-size: 16px;
    line-height: 26px;
    font-weight: 300;
    margin: 0
}

.single_post .blockquote p {
    margin-top: 0 !important
}

.single_post .meta {
    list-style: none;
    padding: 0;
    margin: 0
}

.single_post .meta li {
    display: inline-block;
    margin-right: 15px
}

.single_post .meta li a {
    font-style: italic;
    color: #959595;
    text-decoration: none;
    font-size: 12px
}

.single_post .meta li a i {
    margin-right: 6px;
    font-size: 12px
}

.single_post2 {
    overflow: hidden
}

.single_post2 .content {
    margin-top: 15px;
    margin-bottom: 15px;
    padding-left: 80px;
    position: relative
}

.single_post2 .content .actions_sidebar {
    position: absolute;
    top: 0px;
    left: 0px;
    width: 60px
}

.single_post2 .content .actions_sidebar a {
    display: inline-block;
    width: 100%;
    height: 60px;
    line-height: 60px;
    margin-right: 0;
    text-align: center;
    border-right: 1px solid #e4eaec
}

.single_post2 .content .title {
    font-weight: 100
}

.single_post2 .content .text {
    font-size: 15px
}

.right-box .categories-clouds li {
    display: inline-block;
    margin-bottom: 5px
}

.right-box .categories-clouds li a {
    display: block;
    border: 1px solid;
    padding: 6px 10px;
    border-radius: 3px
}

.right-box .instagram-plugin {
    overflow: hidden
}

.right-box .instagram-plugin li {
    float: left;
    overflow: hidden;
    border: 1px solid #fff
}

.comment-reply li {
    margin-bottom: 15px
}

.comment-reply li:last-child {
    margin-bottom: none
}

.comment-reply li h5 {
    font-size: 18px
}

.comment-reply li p {
    margin-bottom: 0px;
    font-size: 15px;
    color: #777
}

.comment-reply .list-inline li {
    display: inline-block;
    margin: 0;
    padding-right: 20px
}

.comment-reply .list-inline li a {
    font-size: 13px
}

@media (max-width: 640px) {
    .blog-page .left-box .single-comment-box>ul>li {
        padding: 25px 0
    }
    .blog-page .left-box .single-comment-box ul li .icon-box {
        display: inline-block
    }
    .blog-page .left-box .single-comment-box ul li .text-box {
        display: block;
        padding-left: 0;
        margin-top: 10px
    }
    .blog-page .single_post .footer .stats {
        float: none;
        margin-top: 10px
    }
    .blog-page .single_post .body,
    .blog-page .single_post .footer {
        padding: 30px
    }
}
    </style>

</head>
<body>
{% include 'navbar.html' %}
<p></p>
{% block content %}

{% endblock content %}


   <p></p>
<p></p>
{% include 'footer.html' %}
</body>



</html>

usuarios/templates/commentform.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>

{% endblock content %}

usuarios/templates/footer.html
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: #3279a8;">
    <a class="text-white" href=""> © 2022 Copyright: ElOtroTwitter.com / Developed by Erik </a>
  </div>
  <!-- Copyright -->
</footer>

usuarios/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load friendshiptags %}
{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<div class="container">
<ul>


</ul>
    <div class="main-body">

          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active"><a href="">Home</a></li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{request.user.profile.avatar.url}}"  alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ user.username }}</h4>
                      <p class="text-secondary mb-1">Bio Aqui</p>
                      <p class="text-muted font-size-sm">{{ user.email }}</p>
                      <p class="text-muted font-side-sm">Followers: {{user.followers}}</p>
                      <p class="text-muted font-side-sm">Followings: {{user.following}}</p>
                    </div>
                  </div>
                </div>
              </div>
              </div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">

                  <div class="row">
            {% include 'postform.html' %}
                    <h1>TimeLine</h1>
                    <hr>
                  {% for post in object_list %}
                    <div class="col-sm-3">
                        <h6 class="mb-0">{{post.user}}</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                     <a href="{% url 'post_detail' post.id %}">  {{ post.content }} </a>
                     <br>
                     {{ post.cantidad_comentarios }} Comment{{ post.cantidad_comentarios|pluralize }}
                    </div>
                  <hr>
                  {% endfor %}
                  </div>

            <div class="pagination justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

</div>
</div>
</div>
</div>
</div>
</div>
{% endblock content %}

usuarios/templates/like_form.html
<form method="POST" enctype="multipart/form-data">
  
    <!-- Security token -->
    {% csrf_token %}
  
    <!-- Using the formset -->
    {{ form.as_p }}
      
    <input type="submit" value="Submit">
</form>

usuarios/templates/lista_usuarios.html
{% extends 'base.html' %}
{% block content %}
{% load friendshiptags %}
dsfadsfad
<div id="link_nav">
hello {{ user.username }}
<p>solicitudes pendientes de amistad: </p>
{% friends request.user %}
{{friendship_requests}}
<p>Followers: </p>
{% followers request.user %}
{{followers}}
<p>Followings: </p>
{{followings}}

<p>Amigos: </p>

{{amigos}}


{% endblock %}

usuarios/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Pagina de Pruebas Post</title>
</head>
<body>

{% load crispy_forms_tags %}





{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<br>
<br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card-group mb-0">
          <div class="card p-4">
            <div class="card-body">
              <h1>Login</h1>
              <p class="text-muted">Sign In to your account</p>
              <div class="input-group mb-3">
              <form method="post">
              {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">


        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {{ form.username.errors }}

        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

                <div class="col-6 text-right">
                  <button type="button" class="btn btn-link px-0">Forgot password?</button>
                </div>
              </div>
            </div>
          </div>
          <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
            <div class="card-body text-center">
              <div>
                <h2>Sign up</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
              </div>
                <button   type="button"class="btn btn-light"> <a href="/register/"> Register Now! </a> </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

</body>
</html>

usuarios/templates/postform.html
{% load crispy_forms_tags %}


<div class="container">
<div class="col-md-8">
    <form accept-charset="UTF-8" action="/postform/" method="POST">
    <div class="form-group">{% csrf_token %}
    {{ form.content|as_crispy_field }}
    <input type="submit" class="btn btn-primary" value="Send">
        <h6 class="pull-right" id="count_message"></h6>
        <span id="postform">200</span> Character(s) Remaining
</div>
    </form>
</div>


</div>

usuarios/templates/profile-edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Perfil{% endblock %}
{% block content %}
<style>.errorlist{color:red;} label{display:none}</style>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">
            <!-- Previa del avatar -->
            <div class="col-md-2">
              {% if request.user.profile.avatar %}
                <img src="{{request.user.profile.avatar.url}}" class="img-fluid">
                <p class="mt-1">¿Borrar? <input type="checkbox" id="avatar-clear" name="avatar-clear" /></p>
              {% endif %}
            </div>
            <!-- Formulario -->
            <div class="col-md-10">
              <h3>Perfil</h3>
              <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
              {{ form.bio }}
              {{ form.link }}
              <input type="submit" class="btn btn-primary btn-block mt-3" value="Actualizar">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}